import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:gold_flutter/src/amount/amount_formatter_answers.dart';
import 'package:gold_flutter/src/amount/amount_formatter_renderer.dart';
import 'package:test/test.dart';

void main() {
  test('renders owned formatter and focused default expectations', () {
    final files = const AmountFormatterRenderer().render(
      AmountFormatterAnswers.defaults(),
      'sample_app',
    );

    expect(
      files.source,
      startsWith(
        '// Generated by Gold Flutter. Safe to update with gold_flutter.\n'
        "import 'package:intl/intl.dart';",
      ),
    );
    expect(files.source, contains('abstract final class MoneyFormatter'));
    expect(files.source, contains('static String format('));
    expect(files.source, contains('bool showDecimals = true'));
    expect(files.source, contains('static String hidden()'));
    expect(files.test, contains("'₦12.00'"));
    expect(files.test, contains("'₦12.50'"));
    expect(files.test, contains("'₦1,200.00'"));
    expect(files.test, contains("'₦1,200'"));
    expect(files.test, contains("'₦ •••••'"));
  });

  test('escapes hostile Dart strings without syntax errors', () {
    final files = const AmountFormatterRenderer().render(
      AmountFormatterAnswers(
        locale: 'en_US',
        symbol: r"$'\\",
        decimalDigits: 2,
        useGrouping: false,
        hiddenText: r"Bob's $\\ hidden",
      ),
      'sample_app',
    );

    expect(parseString(content: files.source).errors, isEmpty);
    expect(parseString(content: files.test).errors, isEmpty);
  });
}
