import 'package:path/path.dart' as p;

import 'model_class_spec.dart';
import 'model_field_spec.dart';
import 'model_file_spec.dart';

/// Renders the focused defensive test owned by Gold Flutter for one model file.
final class ModelTestRenderer {
  const ModelTestRenderer();

  static const ownershipMarker =
      '// Generated by Gold Flutter. Safe to update with gold_flutter.';

  List<String> inaccessibleSymbols(ModelFileSpec spec) {
    if (spec.rootClassName == null) {
      return List.unmodifiable(
        spec.classes
            .where((model) => _isPrivateIdentifier(model.name))
            .map((model) => model.name),
      );
    }
    final root = _rootModel(spec);
    final symbols = <String>[
      if (_isPrivateIdentifier(root.name)) root.name,
      for (final field in root.fields)
        if (_isPrivateIdentifier(field.name)) '${root.name}.${field.name}',
      for (final field in root.fields)
        if (field.kind == ModelFieldKind.enumeration &&
            _isPrivateType(field.nestedType!))
          field.nestedType!,
    ];
    return List.unmodifiable(symbols);
  }

  String? unsupportedReason(ModelFileSpec spec) {
    if (spec.rootClassName == null) {
      final privateModels = spec.classes
          .where((model) => _isPrivateIdentifier(model.name))
          .map((model) => model.name)
          .join(', ');
      return 'Focused tests require an accessible public root model class.'
          '${privateModels.isEmpty ? '' : ' Found only: $privateModels.'}';
    }
    final root = _rootModel(spec);
    if (!root.supportsDirectObjectFromJson) {
      return 'Focused tests require direct-object ${root.name}.fromJson '
          'semantics; its preserved factory reads a response envelope.';
    }
    final inaccessible = inaccessibleSymbols(spec);
    if (inaccessible.isNotEmpty) {
      return 'Focused tests cannot access library-private symbols: '
          '${inaccessible.join(', ')}';
    }
    return null;
  }

  String testPathFor(String relativeModelPath) {
    final portable = relativeModelPath.replaceAll('\\', '/');
    if (!portable.startsWith('lib/') || !portable.endsWith('.dart')) {
      throw ArgumentError.value(
        relativeModelPath,
        'relativeModelPath',
        'must be a Dart file under lib',
      );
    }
    final withoutExtension = portable.substring(0, portable.length - 5);
    return p.posix.join(
      'test',
      '${withoutExtension.substring('lib/'.length)}_test.dart',
    );
  }

  String render(
    ModelFileSpec spec, {
    required String modelImport,
  }) {
    final unsupported = unsupportedReason(spec);
    if (unsupported != null) {
      throw ArgumentError(unsupported);
    }
    final root = _rootModel(spec);
    final classes = {
      for (final model in spec.classes) model.name: model,
    };
    final buffer = StringBuffer()
      ..writeln(ownershipMarker)
      ..writeln("import 'dart:convert';")
      ..writeln("import 'package:flutter_test/flutter_test.dart';")
      ..writeln('import ${_dartString(modelImport)};')
      ..writeln()
      ..writeln('void main() {')
      ..writeln("  group('${root.name}', () {");

    _writeEmptyTest(buffer, root);
    buffer.writeln();
    _writePrimitiveFallbackTest(buffer, root);
    buffer.writeln();
    _writeNestedAndListFallbackTest(buffer, root);
    buffer.writeln();
    _writeRoundTripTest(
      buffer,
      root,
      classes,
    );

    buffer
      ..writeln('  });')
      ..writeln('}');
    return buffer.toString();
  }
}

ModelClassSpec _rootModel(ModelFileSpec spec) => spec.classes.firstWhere(
      (model) => model.name == spec.rootClassName,
    );

bool _isPrivateIdentifier(String value) => value.startsWith('_');

bool _isPrivateType(String value) =>
    _isPrivateIdentifier(value.split('.').last);

void _writeEmptyTest(StringBuffer buffer, ModelClassSpec root) {
  buffer
    ..writeln("    test('empty uses defensive defaults', () {")
    ..writeln('      final value = ${root.name}.empty();')
    ..writeln()
    ..writeln('      expect(value, isA<${root.name}>());');
  for (final field in root.fields) {
    _writeEmptyExpectation(buffer, field);
  }
  buffer.writeln('    });');
}

void _writeEmptyExpectation(
  StringBuffer buffer,
  ModelFieldSpec field,
) {
  if (field.isNullable) {
    buffer.writeln('      expect(value.${field.name}, isNull);');
    return;
  }
  switch (field.kind) {
    case ModelFieldKind.string:
      buffer.writeln("      expect(value.${field.name}, '');");
    case ModelFieldKind.integer:
    case ModelFieldKind.numeric:
      buffer.writeln('      expect(value.${field.name}, 0);');
    case ModelFieldKind.doubleValue:
      buffer.writeln('      expect(value.${field.name}, 0.0);');
    case ModelFieldKind.boolean:
      buffer.writeln('      expect(value.${field.name}, isFalse);');
    case ModelFieldKind.dateTime:
      buffer.writeln(
        '      expect(value.${field.name}, isA<DateTime>());',
      );
    case ModelFieldKind.nestedModel:
      buffer.writeln(
        '      expect(value.${field.name}.toJson(), '
        'isA<Map<String, dynamic>>());',
      );
    case ModelFieldKind.list:
      buffer.writeln('      expect(value.${field.name}, isEmpty);');
    case ModelFieldKind.enumeration:
      buffer.writeln(
        '      expect(value.${field.name}, isA<${field.nestedType}>());',
      );
  }
}

void _writePrimitiveFallbackTest(
  StringBuffer buffer,
  ModelClassSpec root,
) {
  final primitives = root.fields.where(_isPrimitive).toList();
  buffer
    ..writeln(
      "    test('null and missing primitive JSON uses safe defaults', () {",
    )
    ..writeln('      final missing = ${root.name}.fromJson(const {});')
    ..writeln('      final nulls = ${root.name}.fromJson({');
  for (final field in primitives) {
    buffer.writeln('        ${_dartString(field.jsonKey)}: null,');
  }
  buffer
    ..writeln('      });')
    ..writeln()
    ..writeln('      expect(missing, isA<${root.name}>());')
    ..writeln('      expect(nulls, isA<${root.name}>());');
  for (final field in primitives) {
    _writePrimitiveExpectation(buffer, 'missing', field);
    _writePrimitiveExpectation(buffer, 'nulls', field);
  }
  buffer.writeln('    });');
}

void _writePrimitiveExpectation(
  StringBuffer buffer,
  String value,
  ModelFieldSpec field,
) {
  final access = '$value.${field.name}';
  switch (field.kind) {
    case ModelFieldKind.string:
      buffer.writeln("      expect($access, '');");
    case ModelFieldKind.integer:
    case ModelFieldKind.numeric:
      buffer.writeln(
        field.isNullable
            ? '      expect($access, isNull);'
            : '      expect($access, 0);',
      );
    case ModelFieldKind.doubleValue:
      buffer.writeln(
        field.isNullable
            ? '      expect($access, isNull);'
            : '      expect($access, 0.0);',
      );
    case ModelFieldKind.boolean:
      buffer.writeln('      expect($access, isFalse);');
    case ModelFieldKind.dateTime:
      buffer.writeln(
        field.isNullable
            ? '      expect($access, isNull);'
            : '      expect($access, isA<DateTime>());',
      );
    case ModelFieldKind.enumeration:
      buffer.writeln(
        field.isNullable
            ? '      expect($access, '
                'anyOf(isNull, isA<${field.nestedType}>()));'
            : '      expect($access, isA<${field.nestedType}>());',
      );
    case ModelFieldKind.nestedModel:
    case ModelFieldKind.list:
      throw StateError('Nested values are not primitive test fields.');
  }
}

void _writeNestedAndListFallbackTest(
  StringBuffer buffer,
  ModelClassSpec root,
) {
  final defensiveFields = root.fields
      .where(
        (field) =>
            field.kind == ModelFieldKind.nestedModel ||
            field.kind == ModelFieldKind.list,
      )
      .toList();
  buffer
    ..writeln(
      "    test('nested and list JSON uses defensive fallbacks', () {",
    )
    ..writeln('      final value = ${root.name}.fromJson({');
  for (final field in defensiveFields) {
    final fallback =
        field.kind == ModelFieldKind.list ? "'not-a-list'" : 'null';
    buffer.writeln('        ${_dartString(field.jsonKey)}: $fallback,');
  }
  buffer
    ..writeln('      });')
    ..writeln()
    ..writeln('      expect(value, isA<${root.name}>());');
  for (final field in defensiveFields) {
    if (field.kind == ModelFieldKind.list) {
      buffer.writeln('      expect(value.${field.name}, isEmpty);');
    } else if (field.isNullable) {
      buffer.writeln('      expect(value.${field.name}, isNull);');
    } else {
      buffer.writeln(
        '      expect(value.${field.name}.toJson(), '
        'isA<Map<String, dynamic>>());',
      );
    }
  }
  buffer.writeln('    });');
}

void _writeRoundTripTest(
  StringBuffer buffer,
  ModelClassSpec root,
  Map<String, ModelClassSpec> classes,
) {
  buffer
    ..writeln("    test('JSON string round trip is stable', () {")
    ..writeln('      final original = ${root.name}.fromJson(');
  _writeSampleMap(buffer, root, classes, indent: 8, ancestors: const {});
  buffer
    ..writeln('      );')
    ..writeln('      final encoded = json.encode(original.toJson());')
    ..writeln('      final decoded = ${root.name}.fromJson(')
    ..writeln('        json.decode(encoded) as Map<String, dynamic>,')
    ..writeln('      );')
    ..writeln()
    ..writeln('      expect(decoded.toJson(), original.toJson());')
    ..writeln('    });');
}

void _writeSampleMap(
  StringBuffer buffer,
  ModelClassSpec model,
  Map<String, ModelClassSpec> classes, {
  required int indent,
  required Set<String> ancestors,
}) {
  final padding = ' ' * indent;
  buffer.writeln('$padding<String, dynamic>{');
  final nextAncestors = {...ancestors, model.name};
  for (final field in model.fields) {
    buffer.write('$padding  ${_dartString(field.jsonKey)}: ');
    _writeSampleValue(
      buffer,
      field,
      classes,
      indent: indent + 2,
      ancestors: nextAncestors,
    );
    buffer.writeln(',');
  }
  buffer.write('$padding}');
}

void _writeSampleValue(
  StringBuffer buffer,
  ModelFieldSpec field,
  Map<String, ModelClassSpec> classes, {
  required int indent,
  required Set<String> ancestors,
}) {
  switch (field.kind) {
    case ModelFieldKind.string:
      buffer.write("'sample'");
    case ModelFieldKind.integer:
      buffer.write('42');
    case ModelFieldKind.doubleValue:
      buffer.write('4.25');
    case ModelFieldKind.numeric:
      buffer.write('7');
    case ModelFieldKind.boolean:
      buffer.write('true');
    case ModelFieldKind.dateTime:
      buffer.write("'2024-01-02T03:04:05.000Z'");
    case ModelFieldKind.enumeration:
      buffer.write('null');
    case ModelFieldKind.nestedModel:
      final nested = classes[field.nestedType];
      if (nested == null || ancestors.contains(nested.name)) {
        buffer.write('null');
      } else {
        buffer.writeln();
        _writeSampleMap(
          buffer,
          nested,
          classes,
          indent: indent + 2,
          ancestors: ancestors,
        );
      }
    case ModelFieldKind.list:
      final elementType = field.nestedType!;
      final nested = classes[elementType];
      if (nested != null && !ancestors.contains(nested.name)) {
        buffer.writeln('[');
        _writeSampleMap(
          buffer,
          nested,
          classes,
          indent: indent + 2,
          ancestors: ancestors,
        );
        buffer.write('\n${' ' * indent}]');
      } else {
        buffer.write('[${_primitiveSample(elementType)}]');
      }
  }
}

String _primitiveSample(String type) => switch (type) {
      'String' => "'sample'",
      'int' => '42',
      'double' => '4.25',
      'num' => '7',
      'bool' => 'true',
      'DateTime' => "'2024-01-02T03:04:05.000Z'",
      _ => 'null',
    };

bool _isPrimitive(ModelFieldSpec field) =>
    field.kind != ModelFieldKind.nestedModel &&
    field.kind != ModelFieldKind.list;

String _dartString(String value) {
  final buffer = StringBuffer("'");
  for (final rune in value.runes) {
    switch (rune) {
      case 0x08:
        buffer.write(r'\b');
      case 0x09:
        buffer.write(r'\t');
      case 0x0a:
        buffer.write(r'\n');
      case 0x0d:
        buffer.write(r'\r');
      case 0x24:
        buffer.write(r'\$');
      case 0x27:
        buffer.write(r"\'");
      case 0x5c:
        buffer.write(r'\\');
      case >= 0 && <= 0x1f:
        buffer.write(r'\u{');
        buffer.write(rune.toRadixString(16));
        buffer.write('}');
      default:
        buffer.writeCharCode(rune);
    }
  }
  buffer.write("'");
  return buffer.toString();
}
