import 'package:gold_flutter/src/docs/documentation_generator.dart';
import 'package:gold_flutter/src/docs/documentation_manifest.dart';
import 'package:gold_flutter/src/project/project_inspector.dart';
import 'package:test/test.dart';

import '../../support/project_fixture.dart';

void main() {
  test('preserves user-edited generated docs and updates owned files',
      () async {
    final oldReadme = '<!-- Generated by Gold Flutter. -->\nold\n';
    final manifest = DocumentationManifest(
      version: '0.2.0-dev',
      hashes: {'README.md': DocumentationManifest.sha256Of(oldReadme)},
    );
    final fixture = await ProjectFixture.create(files: {
      'lib/main.dart': 'void main() {}\n',
      'docs/gold_flutter/README.md': 'user edit',
      'docs/gold_flutter/.gold_flutter_docs.json': manifest.encode(),
    });
    addTearDown(fixture.dispose);
    final project = await const ProjectInspector().inspect(fixture.root);

    final plan = await const DocumentationGenerator().plan(project);

    expect(plan.preserved.map((item) => item.subject),
        contains('docs/gold_flutter/README.md'));
    expect(
      plan.files.map((file) => file.relativePath),
      isNot(contains('docs/gold_flutter/README.md')),
    );
    expect(
      plan.files.map((file) => file.relativePath),
      contains('docs/gold_flutter/.gold_flutter_docs.json'),
    );
  });
}
