import 'package:gold_flutter/src/docs/markdown_documentation_renderer.dart';
import 'package:gold_flutter/src/docs/project_documentation.dart';
import 'package:test/test.dart';

void main() {
  test('renders the seven deterministic generated Markdown files', () {
    final snapshot = ProjectDocumentation.normalized(
      projectName: 'sample_app',
      dependencies: {'flutter_riverpod'},
      assets: {'assets/images/'},
      layers: {'core', 'domain'},
      routes: const [
        RouteDocumentation(name: 'HomeRoute', path: '/', isInitial: true),
      ],
      models: const [
        ModelDocumentation(
          name: 'UserModel',
          fields: [ModelFieldDocumentation(name: 'id', type: 'String')],
        ),
      ],
      unknownFacts: const [],
      generatedAtVersion: '0.2.0-dev',
    );

    final files = const MarkdownDocumentationRenderer().render(snapshot);

    expect(files.keys, [
      'docs/gold_flutter/README.md',
      'docs/gold_flutter/architecture.md',
      'docs/gold_flutter/dependencies.md',
      'docs/gold_flutter/routes.md',
      'docs/gold_flutter/assets.md',
      'docs/gold_flutter/models.md',
      'docs/gold_flutter/commands.md',
    ]);
    expect(
        files.values.every(
            (value) => value.startsWith('<!-- Generated by Gold Flutter.')),
        isTrue);
    expect(files['docs/gold_flutter/routes.md'], contains('HomeRoute'));
    expect(files['docs/gold_flutter/models.md'], contains('UserModel'));
  });
}
