import 'project_documentation.dart';

final class MarkdownDocumentationRenderer {
  const MarkdownDocumentationRenderer();

  static const marker =
      '<!-- Generated by Gold Flutter. Edit only outside generated documentation. -->';

  Map<String, String> render(ProjectDocumentation snapshot) => {
        'docs/gold_flutter/README.md': _root(snapshot),
        'docs/gold_flutter/architecture.md': _architecture(snapshot),
        'docs/gold_flutter/dependencies.md': _listPage(
          'Dependencies',
          snapshot.dependencies,
          'No dependencies discovered.',
          snapshot,
        ),
        'docs/gold_flutter/routes.md': _routes(snapshot),
        'docs/gold_flutter/assets.md': _listPage(
          'Assets',
          snapshot.assets,
          'No assets declared.',
          snapshot,
        ),
        'docs/gold_flutter/models.md': _models(snapshot),
        'docs/gold_flutter/commands.md': _commands(snapshot),
      };

  static String _header(String title, ProjectDocumentation snapshot) =>
      '$marker\n\n# $title\n\n'
      '_Generated by Gold Flutter ${snapshot.generatedAtVersion}._\n\n';

  static String _root(ProjectDocumentation snapshot) =>
      '${_header(snapshot.projectName, snapshot)}'
      'Project documentation generated from discoverable local files.\n\n'
      '- [Architecture](architecture.md)\n'
      '- [Dependencies](dependencies.md)\n'
      '- [Routes](routes.md)\n'
      '- [Assets](assets.md)\n'
      '- [Models](models.md)\n'
      '- [Commands](commands.md)\n';

  static String _architecture(ProjectDocumentation snapshot) =>
      '${_header('Architecture', snapshot)}'
      '${snapshot.layers.isEmpty ? 'No Gold Flutter layer directories discovered.\n' : '${snapshot.layers.map((layer) => '- `lib/$layer/`').join('\n')}\n'}'
      '${_unknown(snapshot)}';

  static String _listPage(
    String title,
    List<String> values,
    String empty,
    ProjectDocumentation snapshot,
  ) =>
      '${_header(title, snapshot)}'
      '${values.isEmpty ? '$empty\n' : '${values.map((value) => '- `$value`').join('\n')}\n'}'
      '${_unknown(snapshot)}';

  static String _routes(ProjectDocumentation snapshot) {
    final body = snapshot.routes.isEmpty
        ? 'No routes discovered.\n'
        : '${snapshot.routes.map(
              (route) =>
                  '- `${route.name}`${route.path == null ? '' : ' — `${route.path}`'}${route.isInitial ? ' — initial' : ''}',
            ).join('\n')}\n';
    return '${_header('Routes', snapshot)}$body${_unknown(snapshot)}';
  }

  static String _models(ProjectDocumentation snapshot) {
    if (snapshot.models.isEmpty) {
      return '${_header('Models', snapshot)}No models discovered.\n${_unknown(snapshot)}';
    }
    final buffer = StringBuffer(_header('Models', snapshot));
    for (final model in snapshot.models) {
      buffer.writeln('## ${model.name}');
      buffer.writeln();
      if (model.fields.isEmpty) {
        buffer.writeln('No final fields discovered.');
      } else {
        for (final field in model.fields) {
          buffer.writeln('- `${field.type} ${field.name}`');
        }
      }
      buffer.writeln();
    }
    buffer.write(_unknown(snapshot));
    return buffer.toString();
  }

  static String _commands(ProjectDocumentation snapshot) =>
      '${_header('Gold Flutter Commands', snapshot)}'
      'Run `gold_flutter` or `gold_flutter help` whenever you need the complete '
      'command list. Use `gold_flutter help <command>` for detailed options.\n\n'
      '| Command | Purpose | Run from |\n'
      '| --- | --- | --- |\n'
      '| `gold_flutter create` | Create a new Flutter application. | Parent folder that should contain the new project. |\n'
      '| `gold_flutter doctor` | Check Flutter, Dart, and Git prerequisites. | Anywhere. |\n'
      '| `gold_flutter arrange model --path lib/domain/models/example_model.dart` | Rewrite a supported model safely. | Flutter project root or any folder inside it. |\n'
      '| `gold_flutter optimize` | Run the project-health pipeline. | Flutter project root or any folder inside it. |\n'
      '| `gold_flutter add amount-formatter` | Install the reusable money formatter. | Flutter project root or any folder inside it. |\n'
      '| `gold_flutter docs` | Generate these project documents. | Flutter project root or any folder inside it. |\n\n'
      'Running project commands from the Flutter project root is recommended '
      'for clarity. Gold Flutter searches parent directories for the root.\n';

  static String _unknown(ProjectDocumentation snapshot) => snapshot
          .unknownFacts.isEmpty
      ? ''
      : '\n## Unknown or dynamic facts\n\n${snapshot.unknownFacts.map((fact) => '- $fact').join('\n')}\n';
}
