import '../format/text_escaping.dart';
import 'amount_formatter_answers.dart';

final class AmountFormatterFiles {
  const AmountFormatterFiles({required this.source, required this.test});

  final String source;
  final String test;
}

final class AmountFormatterRenderer {
  const AmountFormatterRenderer();

  static const ownershipMarker =
      '// Generated by Gold Flutter. Safe to update with gold_flutter.';

  AmountFormatterFiles render(
    AmountFormatterAnswers answers,
    String projectName,
  ) {
    final locale = TextEscaping.dartSingleQuoted(answers.locale);
    final symbol = TextEscaping.dartSingleQuoted(answers.symbol);
    final hidden = TextEscaping.dartSingleQuoted(answers.hiddenText);
    final source = '''$ownershipMarker
import 'package:intl/intl.dart';

abstract final class MoneyFormatter {
  static const _locale = '$locale';
  static const _symbol = '$symbol';
  static const _useGrouping = ${answers.useGrouping};

  static final _decimalFormat = NumberFormat.currency(
    locale: _locale,
    symbol: _symbol,
    decimalDigits: ${answers.decimalDigits},
  );
  static final _wholeFormat = NumberFormat.currency(
    locale: _locale,
    symbol: _symbol,
    decimalDigits: 0,
  );

  static String format(num amount, {bool showDecimals = true}) {
    final value = (showDecimals ? _decimalFormat : _wholeFormat).format(amount);
    if (_useGrouping) {
      return value;
    }
    final separator = NumberFormat.decimalPattern(_locale).symbols.GROUP_SEP;
    return value.replaceAll(separator, '');
  }

  static String hidden() => '$hidden';
}
''';
    final exactDefaults = answers.locale == 'en_NG' &&
        answers.symbol == '₦' &&
        answers.decimalDigits == 2 &&
        answers.useGrouping;
    final assertions = exactDefaults
        ? '''
    expect(MoneyFormatter.format(12), '₦12.00');
    expect(MoneyFormatter.format(12.5), '₦12.50');
    expect(MoneyFormatter.format(1200), '₦1,200.00');
    expect(MoneyFormatter.format(1200, showDecimals: false), '₦1,200');'''
        : '''
    expect(MoneyFormatter.format(12), isNotEmpty);
    expect(MoneyFormatter.format(12.5), isNotEmpty);
    expect(MoneyFormatter.format(1200), isNotEmpty);
    expect(
      MoneyFormatter.format(1200, showDecimals: false),
      isNotEmpty,
    );''';
    final test = '''$ownershipMarker
import 'package:$projectName/core/utils/money_formatter.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('formats visible and hidden amounts', () {$assertions
    expect(MoneyFormatter.hidden(), '$hidden');
  });
}
''';
    return AmountFormatterFiles(source: source, test: test);
  }
}
