import 'package:gold_flutter/src/change/change_transaction.dart';
import 'package:gold_flutter/src/cli/gold_flutter_cli.dart';
import 'package:test/test.dart';

import '../support/fake_process_executor.dart';
import '../support/fake_prompt_io.dart';
import '../support/project_fixture.dart';

void main() {
  test('installs owned amount formatter files and verifies them', () async {
    final fixture = await ProjectFixture.create();
    addTearDown(fixture.dispose);
    final executor = FakeProcessExecutor.success({
      'flutter pub add intl': 'added',
      'dart format lib/core/utils/money_formatter.dart '
          'test/core/utils/money_formatter_test.dart': 'formatted',
      'flutter analyze': 'clean',
      'flutter test test/core/utils/money_formatter_test.dart': 'passed',
    });
    final io = FakePromptIO([]);

    final exitCode = await GoldFlutterCli(
      io: io,
      currentDirectory: fixture.root,
      changeTransaction: ChangeTransaction(executor: executor),
    ).run(['add', 'amount-formatter', '--yes']);

    expect(exitCode, 0);
    expect(executor.calls, [
      'flutter pub add intl',
      'dart format lib/core/utils/money_formatter.dart '
          'test/core/utils/money_formatter_test.dart',
      'flutter analyze',
      'flutter test test/core/utils/money_formatter_test.dart',
    ]);
    for (final path in [
      'lib/core/utils/money_formatter.dart',
      'test/core/utils/money_formatter_test.dart',
    ]) {
      expect(await fixture.file(path).exists(), isTrue);
      expect(
        (await fixture.file(path).readAsLines()).first,
        '// Generated by Gold Flutter. Safe to update with gold_flutter.',
      );
    }
  });
}
